export enum APP_CONSTANS {
  PENDING_SEARCH_WORD = "PENDING_SEARCH_WORD",
  AUTH_USER_DATA = "EL_AUTH_USER_DATA",
  AUTH_FUNCIONALITIES = "EL_AUTH_FUNCIONALITIES",
  TXK_NIUBIZ = "TRANSACTION_TOKEN_NIUBIZ",
}
